// This is an autogenerated file from Firebase Studio.
import {z} from 'zod';

/**
 * @fileOverview Schemas for financial recommendations.
 *
 * - FinancialRecommendationsInputSchema - The Zod schema for the input.
 * - FinancialRecommendationsInput - The TypeScript type for the input.
 * - FinancialRecommendationsOutputSchema - The Zod schema for the output.
 * - FinancialRecommendationsOutput - The TypeScript type for the output.
 */

export const FinancialRecommendationsInputSchema = z.object({
  revenue: z
    .number()
    .min(0, 'A receita deve ser um número positivo.')
    .describe('Receita total de todos os canais de venda em BRL.'),
  expenses: z
    .number()
    .min(0, 'As despesas devem ser um número positivo.')
    .describe('Despesas totais, incluindo ingredientes, salários e aluguel em BRL.'),
  ingredientCosts: z
    .number()
    .min(0, 'O custo com ingredientes deve ser um número positivo.')
    .describe('Custo total dos ingredientes em BRL.'),
  wageCosts: z
    .number()
    .min(0, 'O custo com salários deve ser um número positivo.')
    .describe('Custo total com salários em BRL.'),
  rentCosts: z
    .number()
    .min(0, 'O custo com aluguel deve ser um número positivo.')
    .describe('Custo total do aluguel em BRL.'),
  pricingStrategy: z
    .string()
    .min(10, 'A estratégia de preços deve ter pelo menos 10 caracteres.')
    .describe(
      'Estratégia de preços atual para as pizzas, incluindo preço médio por pizza e descontos oferecidos.'
    ),
  recipes: z
    .string()
    .min(10, 'As receitas devem ter pelo menos 10 caracteres.')
    .describe(
      'Descreva as principais receitas de pizza, incluindo ingredientes. Isso ajudará a IA a dar sugestões mais específicas.'
    ),
});
export type FinancialRecommendationsInput = z.infer<typeof FinancialRecommendationsInputSchema>;

export const FinancialRecommendationsOutputSchema = z.object({
  recommendations: z.string().describe('Recomendações geradas por IA para melhorar a lucratividade.'),
});
export type FinancialRecommendationsOutput = z.infer<typeof FinancialRecommendationsOutputSchema>;
